stages:
  - test
  - report

test-job:
  stage: test
  script:
    - docker build -f Dockerfile.base -t base-service .
    - docker compose -f docker-compose.yaml up -d --build
    - pip install -r requirements.txt
    - python -m pytest -m "regression" --alluredir=./allure-results
  after_script:
    - docker compose -f docker-compose.yaml down -v
  artifacts:
    when: always
    paths:
      - allure-results
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"

pages:
  stage: report
  script:
    - mkdir -p public
    - docker run --rm -v "$PWD/allure-results:/allure-results" -v "$PWD/public:/public" frankescobar/allure-docker-service allure generate /allure-results -o /public --clean
  artifacts:
    paths:
      - public
  dependencies:
    - test-job
  rules:
    - if: $CI_COMMIT_BRANCH == "main"