[pytest]
addopts = -s -v
markers =
    gateway: Mark for gateway service tests.
    gateway_operations: Mark for gateway operations service tests.
    gateway_documents: Mark for gateway documents service tests
    gateway_cards: Mark for gateway cards service tests
    gateway_users: Mark for gateway users service tests
    gateway_accounts: Mark for gateway accounts service tests
    regression: Mark for regression tests.
    positive: Mark for positive tests.
    negative: Mark for negative tests.
pythonpath =
    .
    protos/gen
