name: QA Banking
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: self-hosted
    timeout-minutes: 30

    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Build base Docker image
        run: docker build -f Dockerfile.base -t base-service .

      - name: Start test services
        run: docker compose -f docker-compose.yaml up -d --build

      - name: Set up Python virtual environment
        run: |
          python3.12 -m venv venv
          source venv/bin/activate
          python --version
          pip install --upgrade pip

      - name: Install Python dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run regression tests and generate Allure report
        run: |
          source venv/bin/activate
          pytest -m "regression" --alluredir=./allure-results

      - name: Restore Coverage history
        uses: actions/cache/restore@v6
        if: always()
        with:
          path: coverage-history.json
          key: coverage-history-${{ github.run_id }}
          restore-keys: |
            coverage-history-

      - name: Generate Coverage report
        if: always()
        run: |
          source venv/bin/activate
          swagger-coverage-tool save-report

      - name: Cache coverage history
        if: always()
        uses: actions/cache/save@v6
        with:
          path: coverage-history.json
          key: coverage-history-${{ github.run_id }}

      - name: Stop test services
        if: always()
        run: docker compose -f docker-compose.yaml down -v

      - name: Upload Coverage results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: coverage-report
          path: tests/reports/coverage.html

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: allure-results
          path: allure-results

  publish-report:
    if: always()
    needs: [ run-tests ]
    runs-on: self-hosted

    steps:
      - name: Check out repository (gh-pages)
        uses: actions/checkout@v7
        with:
          ref: gh-pages
          path: gh-pages

      - name: Download Allure results
        uses: actions/download-artifact@v8
        with:
          name: allure-results
          path: allure-results

      - name: Generate Allure Report with history in subfolder
        run: |
          REPORT_DIR="allure-history/${{ github.run_number }}"
          HISTORY_DIR="allure-history/history"

          # Создаём папку для истории, если её нет
          mkdir -p "$HISTORY_DIR"

          # Копируем историю из общей папки в allure-results (если она есть)
          if [ -d "$HISTORY_DIR" ] && [ "$(ls -A "$HISTORY_DIR")" ]; then
            echo "Copying history from $HISTORY_DIR to allure-results/history"
            mkdir -p allure-results/history
            cp -r "$HISTORY_DIR/"* allure-results/history/
          else
            echo "No previous history found, starting fresh."
          fi

          if [ -d "allure-results" ] && [ "$(ls -A allure-results)" ]; then
            allure generate allure-results -o "$REPORT_DIR" --clean
          else
            echo "No test results found, creating empty report."
            mkdir -p "$REPORT_DIR"
            echo '<html><body><h1>No tests executed</h1></body></html>' > "$REPORT_DIR/index.html"
          fi

          if [ -d "$REPORT_DIR/history" ]; then
            echo "Updating global history from $REPORT_DIR/history"
            mkdir -p "$HISTORY_DIR"
            cp -r "$REPORT_DIR/history/"* "$HISTORY_DIR/"
          fi

          echo "<html><head><meta http-equiv='refresh' content='0; url=./${{ github.run_number }}/index.html' /></head><body><a href='./${{ github.run_number }}/index.html'>Latest report</a></body></html>" > allure-history/index.html

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./allure-history
          keep_files: true
          force_orphan: false